// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3p9ev0o8ubbhZMU2wtiyCh0oXiNCNW_o',
    appId: '1:742877390172:web:e0d8b7346fbe64c7c80d99',
    messagingSenderId: '742877390172',
    projectId: 'summerclass2026-1',
    authDomain: 'summerclass2026-1.firebaseapp.com',
    storageBucket: 'summerclass2026-1.firebasestorage.app',
    measurementId: 'G-EZ075MVN22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJUayZew9vg4aiZUIngxulPqB1jrmo1PA',
    appId: '1:742877390172:android:1b0289febe011b7dc80d99',
    messagingSenderId: '742877390172',
    projectId: 'summerclass2026-1',
    storageBucket: 'summerclass2026-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaSZGIRWgL_95rTD-eP4xnlYM83kP11Pw',
    appId: '1:742877390172:ios:e65bee81c2818245c80d99',
    messagingSenderId: '742877390172',
    projectId: 'summerclass2026-1',
    storageBucket: 'summerclass2026-1.firebasestorage.app',
    iosBundleId: 'com.example.summerclass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaSZGIRWgL_95rTD-eP4xnlYM83kP11Pw',
    appId: '1:742877390172:ios:e65bee81c2818245c80d99',
    messagingSenderId: '742877390172',
    projectId: 'summerclass2026-1',
    storageBucket: 'summerclass2026-1.firebasestorage.app',
    iosBundleId: 'com.example.summerclass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3p9ev0o8ubbhZMU2wtiyCh0oXiNCNW_o',
    appId: '1:742877390172:web:2e6eee987c5012d6c80d99',
    messagingSenderId: '742877390172',
    projectId: 'summerclass2026-1',
    authDomain: 'summerclass2026-1.firebaseapp.com',
    storageBucket: 'summerclass2026-1.firebasestorage.app',
    measurementId: 'G-K2LXM0ZE3J',
  );
}
